### ISSUE TITLE
Executing multiple subsequent transactions (via commands) seems to lead to duplicate event insertion

### ISSUE THREAD

**Issue by Ocramius** [prooph/event-store#152]
I'm a bit puzzled by this one, as it seems to be caused by shared state that isn't in my application layer (as it seems).

tl;dr:

```php
$transactionManager = new TransactionManager();

$transactionManager->setUp($container->get(EventStore::class));

$commandBus->utilize($transactionManager);

$commandBus->dispatch(new CommandThatCreatesAggregateOfTypeA());
// events of the previous `$commandBus->dispatch` are being inserted also
// when the following command is dispatched
$commandBus->dispatch(new CommandThatCreatesAggregateOfTypeB()); 
```

Here's an example trace:

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: event_stream.aggregate_id, event_stream.aggregate_type, event_stream.version in vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(695): Doctrine\DBAL\Connection->executeUpdate('INSERT INTO eve...', Array, Array)
#3 vendor/prooph/event-store-doctrine-adapter/src/DoctrineEventStoreAdapter.php(320): Doctrine\DBAL\Connection->insert('event_stream', Array)
#4 vendor/prooph/event-store-doctrine-adapter/src/DoctrineEventStoreAdapter.php(114): Prooph\EventStore\Adapter\Doctrine\DoctrineEventStoreAdapter->insertEvent(Object(Prooph\EventStore\Stream\StreamName), Object(MyProjectIo\Domain\DomainEvent\Github\HookWasDispatched))
#5 vendor/prooph/event-store/src/EventStore.php(147): Prooph\EventStore\Adapter\Doctrine\DoctrineEventStoreAdapter->appendTo(Object(Prooph\EventStore\Stream\StreamName), Object(ArrayIterator))
#6 vendor/prooph/event-store/src/Aggregate/AggregateRepository.php(110): Prooph\EventStore\EventStore->appendTo(Object(Prooph\EventStore\Stream\StreamName), Object(ArrayIterator))
#7 vendor/prooph/common/src/Event/ProophActionEventEmitter.php(52): Prooph\EventStore\Aggregate\AggregateRepository->addPendingEventsToStream(Object(Prooph\Common\Event\DefaultActionEvent))
#8 vendor/prooph/event-store/src/EventStore.php(339): Prooph\Common\Event\ProophActionEventEmitter->dispatch(Object(Prooph\Common\Event\DefaultActionEvent))
#9 vendor/prooph/event-store-bus-bridge/src/TransactionManager.php(129): Prooph\EventStore\EventStore->commit()
#10 vendor/prooph/common/src/Event/ProophActionEventEmitter.php(52): Prooph\EventStoreBusBridge\TransactionManager->onFinalize(Object(Prooph\Common\Event\DefaultActionEvent))
#11 vendor/prooph/service-bus/src/MessageBus.php(151): Prooph\Common\Event\ProophActionEventEmitter->dispatch(Object(Prooph\Common\Event\DefaultActionEvent))
#12 vendor/prooph/service-bus/src/CommandBus.php(122): Prooph\ServiceBus\MessageBus->triggerFinalize(Object(Prooph\Common\Event\DefaultActionEvent))
#13 vendor/prooph/service-bus/src/CommandBus.php(75): Prooph\ServiceBus\CommandBus->processCommand(Object(MyProjectIo\Domain\Command\Github\RunHook))
#14 src/MyProjectIo/Factory/Infrastructure/Messaging/CommandBusFactory.php(33): Prooph\ServiceBus\CommandBus->dispatch(Object(MyProjectIo\Domain\Command\Github\RunHook))
```

The SQL-level failure seems to be as following:

```
INSERT INTO event_stream (event_id, version, event_name, payload, created_at, aggregate_id, aggregate_type) VALUES (?, ?, ?, ?, ?, ?, ?)'
with params
["f54e25d0-b866-463a-b59b-a739de163fc1", 0, "MyProjectIo\\Domain\\DomainEvent\\Github\\HookWasDispatched", "{\"stuff\":\"stuff\"}", "2016-02-09T00:25:50.224500", "ccbc8d59-eabb-4f9b-85b2-e1fe5adf907a", "MyProjectIo\\Domain\\Aggregate\\GithubRepository"]
```

Please notice `TheWrongAggregate` at the end of the params - it is trying to store the 

I realize that this isn't much to get get started, but I'm really confused about why the events from a previous transaction are being inserted also in the second transaction. Any pointers on where to look at?

For a quick reference on how this was set up, here's the factory responsible for creating my command bus:

```php
    public function __invoke(ContainerInterface $container) : callable
    {
        $commandBus = new CommandBus();

        $commandBus->utilize(new ServiceLocatorPlugin($container));
        $commandBus->utilize($this->buildCommandRouter());

        $transactionManager = new TransactionManager();

        $transactionManager->setUp($container->get(EventStore::class));

        $commandBus->utilize($transactionManager);

        return function ($command) use ($commandBus) {
            $commandBus->dispatch($command);
        };
    }
```

**Comment by prolic** [comment]
I cannot reproduce this issue, I created the following test-script, based on proophessor-do (see https://github.com/prooph/proophessor-do):

    <?php
    
    // Setup autoloading
    require 'vendor/autoload.php';
    
    $container = include 'config/services.php';
    
    $app = $container->get('Zend\Expressive\Application');
    
    $commandBus = $app->getContainer()->get(\Prooph\ServiceBus\CommandBus::class);
    
    $call = function(\Prooph\Common\Messaging\Command $command) use ($commandBus) {
        $commandBus->dispatch($command);
    };
    
    $userId1 = \Prooph\ProophessorDo\Model\User\UserId::generate();
    $userId2 = \Prooph\ProophessorDo\Model\User\UserId::generate();
    
    $call(\Prooph\ProophessorDo\Model\User\Command\RegisterUser::withData(
        $userId1->toString(),
        'sasa',
        'foo@bar.com'
    ));
    
    $call(\Prooph\ProophessorDo\Model\User\Command\RegisterUser::withData(
        $userId2->toString(),
        'sasa2',
        'foo@bar2.com'
    ));

Everything works as expected. Can you provide more details?

**Comment by Ocramius** [comment]
I'll try doing that. Is there any specific way to check which events are going to be persisted?

**Comment by prolic** [comment]
According to your trace AggregateRepository::addPendingEventsToStream() is called, so I would var_dump in this method, to see what is persisted, see: https://github.com/prooph/event-store/blob/master/src/Aggregate/AggregateRepository.php#L96

**Comment by prolic** [comment]
You can also attach an event listener to the event-store to get the information, but debugging is faster to do :)

**Comment by Ocramius** [comment]
Turns out that this was my own mis-interpretation of how popping events from an aggregate works.

Basically, I was doing this:

```php
class Repository implements YaddaYadda
{
    public static function fromEvents(\Traversable $recordedEvents) : self
    {
        $instance = new self();

        foreach ($events as $event) {
            // replay status here
            $instance->events[] = $event; // wrong - this is not an event that should be popped
        }

        return $events;
    }
    public function popRecordedEvents() : array
    {
        $events = $this->events;

        $this->events = [];

        return $events;
    }
}
```

I was confused because I didn't think that I was re-constructing any aggregates in that piece of code, but it turns out that I was wrong ^ 2.
This can be marked as invalid.

**Comment by prolic** [comment]
I see, f.y.i.: https://github.com/prooph/event-sourcing/blob/master/src/AggregateRoot.php#L41

**Comment by Ocramius** [comment]
Yeah, probably going to inherit from it to avoid having to deal with this again :-)
